### ISSUE TITLE
Change the branch name

### ISSUE THREAD

**Issue by JinmanX** [JinmanX/Data-Fair-G18#3]
There is a small change so we can use `+GitRepo` on Edina. (We cannot upload `main` branch)
Github changed the default branch name recently to use neutral term.

> https://www.zdnet.com/article/github-to-replace-master-with-main-starting-next-month/

**Comment by linnva** [comment]
Thanks for letting us know! I switched between Edina and my local kernel, so don't be surprised when you see another name's authentication instead of linnva (Vanessa Neeff
