### ISSUE TITLE
Worries about map sources

### ISSUE THREAD

**Issue by JinmanX** [JinmanX/Data-Fair-G18#4]
- Can we use Mapbox, OpenStreetMap or Google on our website? Not sure yet, `Google API` should be paid. I notice some example map can be interactive which is a good sign.
- Since we don't have accurate location (During my own data mining, I notice the locations are from the user account page which normally are the home address or fake address of users.), some boundary map is not so accurate. Maybe we can just use color to show difference with your recommended classification as legends. So I mean for location, we can focus on tweets and hashtags.
- I'm not so sure should we use other visulisations besides geomap, our data holder didn't tell so clearly about that.

**Comment by Hazelll-Liu** [comment]
Since we are lack of longitude and latitude data, how about using a larger range like a certain country to present the data? 
I've found some map resources in this link: https://blog.csdn.net/cune1359/article/details/106848489

**Comment by linnva** [comment]
we can add the longitude and latitude data using a python package, I mentioned that in the plotly issue

**Comment by JinmanX** [comment]
> we can add the longitude and latitude data using a python package, I mentioned that in the plotly issue

I mean that some locations just include Countries but some are cities but longitude and latitude data is more accurate like a dot on map, maybe we just ignore this difference for now.
