### ISSUE TITLE
About the website design

### ISSUE THREAD

**Issue by Hazelll-Liu** [JinmanX/Data-Fair-G18#6]
How do you think we have a catalog before all the contents?
Any suggestions on our web ui please tell me.
![WEB-01](https://user-images.githubusercontent.com/73325826/101285181-c928ca00-381e-11eb-9c52-e716156fbd2d.png)
![WEB-02](https://user-images.githubusercontent.com/73325826/101285185-cd54e780-381e-11eb-8bf8-98f7542c12f0.png)

**Comment by Hazelll-Liu** [comment]
![image](https://user-images.githubusercontent.com/73325826/101285235-0f7e2900-381f-11eb-8533-74fd0e434e1c.png)
By the way, there's some chinese on the page, do you know how to remove that?

**Comment by JinmanX** [comment]
Hey I used another template to solve the problem!
