### ISSUE TITLE
How to realize topic clustering?

### ISSUE THREAD

**Issue by JinmanX** [JinmanX/Data-Fair-G18#7]
The two most common methods of topic analysis are topic modeling and topic classification. Topic modeling a text analysis technique that uses unsupervised machine learning to process text by topic or subject and cluster and categorize similar words and phrases, without the need to create defined tags (categories) ahead of time. With topic classification or topic extraction, on the other hand, you must pre-define the tags, use them to train a classification model, and the model will then categorize your texts (tweets) into the tags you set up.

**Comment by linnva** [comment]
What about semi-supervised methods? Maybe that is something we could look into in the future

**Comment by Hazelll-Liu** [comment]
Maybe topic modeling is more suitable for us, because it may need a great deal of effort to pre-define the tags based on the complexity for tweets.
